### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by Festouille** [Valentin-alix/Bot-Dofus-Mitm#1]
Yo, l'hdv sniffer m'intéresse ducoup j'ai décidé d'utiliser ton projet, mais j'ai un soucis en lancant init.py : 

```
PS C:\Users\akram\UIRPLANNIN2\MitmDofusBot-main> & C:/Users/akram/AppData/Local/Programs/Python/Python311/python.exe c:/Users/akram/UIRPLANNIN2/MitmDofusBot-main/MitmDofusBot-main/app/scripts/init.py
Traceback (most recent call last):
  File "c:\Users\akram\UIRPLANNIN2\MitmDofusBot-main\MitmDofusBot-main\app\scripts\init.py", line 7, in <module>
    from app.scripts.decompile_code_source import get_as_scripts
ModuleNotFoundError: No module named 'app'
```
J'attends ta réponse, ty

**Comment by pradzgaming** [comment]
Yep pareil petit soucis si il y a la possibilité de link ton discord ! ty

**Comment by Festouille** [comment]
Yep ça serait cool de discuter avec toi Valentin !

**Comment by Valentin-alix** [comment]
Salut, oui le fichier d'initialisation contient quelques erreur qui sont résolus mais que je n'ai pas encore push, 
ca devrait être bon d'ici ce soir ou demain

**Comment by Valentin-alix** [comment]
J'ai mis à jour le script, il y a juste besoin d'exécuter le init.bat

**Comment by Valentin-alix** [comment]
mon id discord si vous voulez discuter : ezrealeeeeeeeeeeeeeeuuuuuueuuuuu

**Comment by Festouille** [comment]
Re ! L'erreur `ModuleNotFoundError: No module named 'app'` est réglé mais j'ai cette erreur maintenant : 

```
PS C:\Users\akram\MitmDofusBot-main> & C:/Python312/python.exe c:/Users/akram/MitmDofusBot-main/app/scripts/init.py
Error: Unable to access jarfile None
Traceback (most recent call last):
  File "c:\Users\akram\MitmDofusBot-main\app\network\protocol\build_protocol.py", line 8, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
Traceback (most recent call last):
  File "c:\Users\akram\MitmDofusBot-main\app\scripts\init.py", line 25, in <module>
    launch_generator()
  File "c:\Users\akram\MitmDofusBot-main\app\scripts\generate_python_class.py", line 175, in launch_generator
    create_python_class_dofus_file(base_path_output)
  File "c:\Users\akram\MitmDofusBot-main\app\scripts\generate_python_class.py", line 68, in create_python_class_dofus_file
    with open(protocol_json_path) as protocol_json_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\akram\\MitmDofusBot-main\\app\\network\\protocol\\protocol_type.json'
```

ça indique que il n'y a pas de fichier protocol_type.json dans cette directory (ce qui est vrai). Merci

**Comment by Valentin-alix** [comment]
il faut que tu exécute le fichier init.bat et non le init.py dans le dossier scripts, pense également a créer le fichier .env à la racine du projet et a installer JPEXS Free Flash Decompiler comme indiquer dans le README, car tu as cette erreur : 
`Error: Unable to access jarfile None` qui indique que le script ne trouve pas ffdec : [jpex free flash decompile](https://github.com/jindrapetrik/jpexs-decompiler/releases/tag/version20.0.0)

**Comment by Festouille** [comment]
j'ai bien lancé le init.bat, et j'ai installer JPEXS Free Flash Decompiler 
![image](https://github.com/Valentin-alix/MitmDofusBot/assets/115322112/9f3ba578-8488-4d00-a106-5d48d511b615)

**Comment by Festouille** [comment]
J'ai une erreur en installant quelques requirements, mais je peux pas savoir vu que la fenêtre se ferme directement après avoir afficher l'erreur (tout ça en executant le fichier .Bat)

**Comment by Festouille** [comment]
![image](https://github.com/Valentin-alix/MitmDofusBot/assets/115322112/57008836-be0a-4fc9-94c6-c3667c7c84dc)

J'ai ça en lançant le fichier .bat

**Comment by Festouille** [comment]
![image](https://github.com/Valentin-alix/MitmDofusBot/assets/115322112/b0669d45-560d-4576-8e8a-03ec67e2e4fb)

J'ai bien indiquer le bon chemin pour le ffdec.jar

**Comment by Festouille** [comment]
et quand je lance le test j'ai 3 Fatal Errors : `PS C:\Users\akram\MitmDofusBot-main> python -m unittest                                                                            
EEE
======================================================================
ERROR: app.test.test_selling (unittest.loader._FailedTest.app.test.test_selling)
----------------------------------------------------------------------
ImportError: Failed to import test module: app.test.test_selling
Traceback (most recent call last):
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "C:\Users\akram\MitmDofusBot-main\app\test\test_selling.py", line 3, in <module>
    from app.modules.hdv.selling_hdv import SellingHdv
  File "C:\Users\akram\MitmDofusBot-main\app\modules\hdv\selling_hdv.py", line 11, in <module>
    from app.types_.dofus.scripts.com.ankamagames.dofus.network.messages.game.inventory.exchanges.ExchangeBidHousePriceMessage import (
ModuleNotFoundError: No module named 'app.types_.dofus'


======================================================================
ERROR: app.test.test_sniffer (unittest.loader._FailedTest.app.test.test_sniffer)
----------------------------------------------------------------------
ImportError: Failed to import test module: app.test.test_sniffer
Traceback (most recent call last):
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "C:\Users\akram\MitmDofusBot-main\app\test\test_sniffer.py", line 6, in <module>
    import app.network.sniffer as sniffer
  File "C:\Users\akram\MitmDofusBot-main\app\network\sniffer.py", line 7, in <module>
    from app.network.parser import MessageRawDataParser
  File "C:\Users\akram\MitmDofusBot-main\app\network\parser.py", line 4, in <module>
    from app.network.handler import Handler
  File "C:\Users\akram\MitmDofusBot-main\app\network\handler.py", line 5, in <module>
    from app.modules.character import Character
  File "C:\Users\akram\MitmDofusBot-main\app\modules\character.py", line 1, in <module>
    from app.types_.dofus.scripts.com.ankamagames.dofus.network.types.game.data.items.ObjectItem import (
ModuleNotFoundError: No module named 'app.types_.dofus'


======================================================================
ERROR: test_object_move_price (app.test.test_write.TestPriceQuantity.test_object_move_price)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\akram\MitmDofusBot-main\app\test\test_write.py", line 8, in test_object_move_price
    data = protocol.write("ExchangeObjectMovePricedMessage", {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akram\MitmDofusBot-main\app\network\protocol\protocol.py", line 108, in write
    _type = types[_type]
            ~~~~~^^^^^^^
KeyError: 'ExchangeObjectMovePricedMessage'

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
`

**Comment by Festouille** [comment]
J'ai ça en lancant le test 
```
PS C:\Users\akram\MitmDofusBot-main> python -m unittest                                                                            
EEE
======================================================================
ERROR: app.test.test_selling (unittest.loader._FailedTest.app.test.test_selling)
----------------------------------------------------------------------
ImportError: Failed to import test module: app.test.test_selling
Traceback (most recent call last):
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "C:\Users\akram\MitmDofusBot-main\app\test\test_selling.py", line 3, in <module>
    from app.modules.hdv.selling_hdv import SellingHdv
  File "C:\Users\akram\MitmDofusBot-main\app\modules\hdv\selling_hdv.py", line 11, in <module>
    from app.types_.dofus.scripts.com.ankamagames.dofus.network.messages.game.inventory.exchanges.ExchangeBidHousePriceMessage import (
ModuleNotFoundError: No module named 'app.types_.dofus'


======================================================================
ERROR: app.test.test_sniffer (unittest.loader._FailedTest.app.test.test_sniffer)
----------------------------------------------------------------------
ImportError: Failed to import test module: app.test.test_sniffer
Traceback (most recent call last):
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akram\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "C:\Users\akram\MitmDofusBot-main\app\test\test_sniffer.py", line 6, in <module>
    import app.network.sniffer as sniffer
  File "C:\Users\akram\MitmDofusBot-main\app\network\sniffer.py", line 7, in <module>
    from app.network.parser import MessageRawDataParser
  File "C:\Users\akram\MitmDofusBot-main\app\network\parser.py", line 4, in <module>
    from app.network.handler import Handler
  File "C:\Users\akram\MitmDofusBot-main\app\network\handler.py", line 5, in <module>
    from app.modules.character import Character
  File "C:\Users\akram\MitmDofusBot-main\app\modules\character.py", line 1, in <module>
    from app.types_.dofus.scripts.com.ankamagames.dofus.network.types.game.data.items.ObjectItem import (
ModuleNotFoundError: No module named 'app.types_.dofus'


======================================================================
ERROR: test_object_move_price (app.test.test_write.TestPriceQuantity.test_object_move_price)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\akram\MitmDofusBot-main\app\test\test_write.py", line 8, in test_object_move_price
    data = protocol.write("ExchangeObjectMovePricedMessage", {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akram\MitmDofusBot-main\app\network\protocol\protocol.py", line 108, in write
    _type = types[_type]
            ~~~~~^^^^^^^
KeyError: 'ExchangeObjectMovePricedMessage'

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)

```

**Comment by Valentin-alix** [comment]
Tu as essayer d'exécuter JPEXS Free flash decompiler pour voir si il n'y a pas de problème ?
sinon les fixtures pour les tests ne sont pas à jour dans tous les cas car le protocole de dofus change à chaque maj, même si c'est pas lié à ton problème

**Comment by Festouille** [comment]
Oui le JPEXS FFD s'ouvre sans problème : 
![image](https://github.com/Valentin-alix/MitmDofusBot/assets/115322112/1623f6ba-aa4c-4759-8570-82464902a2ee)

**Comment by pradzgaming** [comment]
le nom du .env n'a pas d'importance ? pour ma part toujours la meme erreur le .bat qui affiche toutes les erreur et se ferme, meme en ayant up ce que tu a ajouter

**Comment by Valentin-alix** [comment]
A toi de voir pourquoi ca ne trouve pas le fichier j'ai mis sa comme .env pour l'exemple :
 ```
D2O_FOLDER="C:\\Users\\Valentin\\AppData\\Local\\Ankama\\Dofus\\data\\common"
D2P_FOLDER="C:\\Users\\Valentin\\AppData\\Local\\Ankama\\Dofus\\content\\gfx\\items"
D2P_FOLDER2="C:\\Users\\Valentin\\AppData\\Local\\Ankama\\Dofus\\content\\gfx\\sprites"
D2I_FILE="C:\\Users\\Valentin\\AppData\\Local\\Ankama\\Dofus\\data\\i18n\\i18n_fr.d2i"
DOFUS_INVOKER="C:\\Users\\Valentin\\AppData\\Local\\Ankama\\Dofus\\DofusInvoker.swf"
FFDECJAR_PATH="C:\\Program Files (x86)\\FFDec\\ffdec.jar"
```

> Oui le JPEXS FFD s'ouvre sans problème : ![image](https://user-images.githubusercontent.com/115322112/283938952-1623f6ba-aa4c-4759-8570-82464902a2ee.png)

**Comment by Valentin-alix** [comment]
> le nom du .env n'a pas d'importance ? pour ma part toujours la meme erreur le .bat qui affiche toutes les erreur et se ferme, meme en ayant up ce que tu a ajouter

Un fichier .env avec vos chemins correspondant, j'ai essayer d'initialiser le projet en partant de 0 et je n'ai pas eu de problème, soit c'est un problème de compatibilité avec vos os soit c'est le mauvais chemin dans le .env

**Comment by pradzgaming** [comment]
![IMG_5020](https://github.com/Valentin-alix/MitmDofusBot/assets/88455855/7633ac75-2cb9-4c66-8876-acff7e0bbe63)

Désoler jai pris avec le tel car jai un soucis avec discord sur PC mais jai bien vérifier les chemins tout est ok jai pris le screen il m'affiche ça en erreur

**Comment by Festouille** [comment]
![image](https://github.com/Valentin-alix/MitmDofusBot/assets/115322112/639219ea-70e2-4f7b-ac21-b821127c5a5b)

Quand je copie le chemin d'accès ça me met ça : "C:\Program Files (x86)\FFDec\ffdec.jar" Alors que c'est marqué Programmes et non Program Files, c'est normal ?
