### ISSUE TITLE
Dofus.exe en boucle

### ISSUE THREAD

**Issue by Zaibla** [Valentin-alix/Bot-Dofus-Mitm#3]
Hello!

L'installation s'est bien déroulé, mais en lançant le bot, il m'affiche en boucle 

![pb bot](https://github.com/user-attachments/assets/7890e9b0-7c74-4913-adb4-9b1c93e5197d)

Tu pourrais m'aider stp ?

**Comment by Zaibla** [comment]
J'ai plus ce soucis car je n'avais pas compris qu'il fallait lancer dofus et ensuite le script, mais il y a un message d'erreur avec Frida 

```
> #←[1;33m📢 Tips:←[0m QFluentWidgets Pro is now released. Click ←[1;96mhttps://qfluentwidgets.com/pages/pro←[0m to learn more about it.
> 
> Démarrage de l'attente pour Dofus.exe...
> Dofus.exe détecté. Démarrage du serveur proxy.
> Traceback (most recent call last):
>   File "C:\Users\Shadow\Downloads\Bot-Dofus-Mitm-main\Bot-Dofus-Mitm-main\app\network\mitm.py", line 66, in launch
>     fritm.hook("Dofus.exe", 8080, "port==5555")
>   File "C:\Users\Shadow\AppData\Local\Programs\Python\Python312\Lib\site-packages\fritm\hook.py", line 19, in hook
>     session = frida.attach(target)
>               ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Shadow\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\__init__.py", line 95, in attach
>     return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Shadow\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 86, in wrapper
>     return f(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Shadow\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 1071, in attach
>     return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
>                                      ^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Shadow\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 1193, in _pid_of
>     return self.get_process(target).pid
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Shadow\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 86, in wrapper
>     return f(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Shadow\AppData\Local\Programs\Python\Python312\Lib\site-packages\frida\core.py", line 967, in get_process
>     raise _frida.ProcessNotFoundError(f"ambiguous name; it matches: {matches_list}")
> frida.ProcessNotFoundError: ambiguous name; it matches: Dofus.exe (pid: 18028), Dofus.exe (pid: 20368)
```

**Comment by Valentin-alix** [comment]
Salut, tu peux lancer le script puis Dofus, et lance une seule instance de Dofus, le bot n'est pas prévu pour être multi compte.

**Comment by Zaibla** [comment]
Ok, maintenant j'ai ça : 

(.venv) C:\Users\Shadow\Downloads\Bot-Dofus-Mitm-main\Bot-Dofus-Mitm-main>python app/__main__.py

```
#←[1;33m📢 Tips:←[0m QFluentWidgets Pro is now released. Click ←[1;96mhttps://qfluentwidgets.com/pages/pro←[0m to learn more about it.

Démarrage de l'attente pour Dofus.exe...
Dofus.exe détecté. Démarrage du serveur proxy.
Traceback (most recent call last):
  File "C:\Users\Shadow\Downloads\Bot-Dofus-Mitm-main\Bot-Dofus-Mitm-main\app\network\mitm.py", line 66, in launch
    fritm.hook("Dofus.exe", 8080, "port==5555")
  File "C:\Users\Shadow\Downloads\Bot-Dofus-Mitm-main\Bot-Dofus-Mitm-main\.venv\Lib\site-packages\fritm\hook.py", line 19, in hook
    session = frida.attach(target)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\Bot-Dofus-Mitm-main\Bot-Dofus-Mitm-main\.venv\Lib\site-packages\frida\__init__.py", line 95, in attach
    return get_local_device().attach(target, realm=realm, persist_timeout=persist_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\Bot-Dofus-Mitm-main\Bot-Dofus-Mitm-main\.venv\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shadow\Downloads\Bot-Dofus-Mitm-main\Bot-Dofus-Mitm-main\.venv\Lib\site-packages\frida\core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: unexpectedly failed with error code: 0x00000057
```

**Comment by Zaibla** [comment]
Je comprends pas le message d'erreur frida.NotSupportedError: unexpectedly failed with error code: 0x00000057

**Comment by Valentin-alix** [comment]
Cette version de Frida avait un problème avec une version de windows 10 apparemment, j'ai mis à jour les dépendances, tu peux récupérer les changements, supprimer le dossier .venv et refaire une installe et ca devrait être bon

**Comment by Zaibla** [comment]
Hello !

Y'a du mieux ! Merci pour les modifications. J'arrive à lancer le bot, par contre quand je lance Dofus, ça charge à l'infini et ça ne me connecte pas 

![latence connexion](https://github.com/user-attachments/assets/3397a268-7c48-42af-a1ba-b0955ab01d65)

J'ai bien réessayer à chaque fois, en relançant même le CMD, j'ai systématiquement le ▲MO

Le réseau est ok de mon côté
